import type { SiteData } from '../types'
import { settings, originalGalleryImages } from './shared'

const deGallery: SiteData['gallery'] = originalGalleryImages.map(([title, alt, image]: string[], index: number) => ({
  id: `gallery-original-de-${index + 1}`,
  locale: 'de',
  title,
  alt,
  image,
  sort: index + 1,
}))

export const fallbackDe: SiteData = {
  settings,
  source: 'fallback',
  navigation: [
    { id: 'nav-home-de', locale: 'de', label: 'Startseite', href: '/de', sort: 1 },
    { id: 'nav-om-oss-de', locale: 'de', label: 'Über uns', href: '/de/uber-uns', sort: 2 },
    { id: 'nav-services-de', locale: 'de', label: 'Dienstleistungen', href: '/de/dienstleistungen', sort: 3 },
    { id: 'nav-pakker-de', locale: 'de', label: 'Pakete', href: '/de/pakete', sort: 4 },
    { id: 'nav-maxi-taxi-de', locale: 'de', label: 'Maxi Taxi', href: '/de/maxi-taxi', sort: 6 },
    { id: 'nav-bli-sjafor-de', locale: 'de', label: 'Fahrer werden', href: '/de/fahrer-werden', sort: 7 },
    { id: 'nav-gallery-de', locale: 'de', label: 'Galerie', href: '/de/galerie', sort: 8 },
    { id: 'nav-ris-ros-de', locale: 'de', label: 'Feedback', href: '/de/ris-ros', sort: 9 },
    { id: 'nav-contact-de', locale: 'de', label: 'Kontakt', href: '/de/kontakt', sort: 10 },
  ],
  pages: [
    {
      id: 'home-de',
      locale: 'de',
      slug: 'home',
      eyebrow: 'Lokales Taxiunternehmen in Voss',
      title: 'Fahren Sie sicher mit uns, aus Voss.',
      summary:
        'Voss Taxi bietet Limousinen, Minivans, Maxi-Taxis, Minibusse und Rollstuhltransporte für Einheimische und Besucher.',
      hero_image: settings.hero_media,
      blocks: [
        {
          type: 'rich_text',
          title: 'Mit Vertrauen buchen',
          body: 'Wir haben Fahrzeuge für alle Arten von Aufträgen und bringen Sie sicher zu Zügen, Hotels, Hütten, Bergen und Veranstaltungen.',
        },
        {
          type: 'rich_text',
          title: 'Per App buchen',
          body: '### Snappy Taxi\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/snappy-taxi/id6479620974) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=no.snappy.snappy.taxi&hl=no)\n\n### Buchen Sie ein Taxi in der VY-App\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/vy-nsb/id439655098) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=com.intele.nsbmob.app)'
        },
        {
          type: 'cta',
          title: 'Telefonisch oder per Kalkulator buchen',
          body: 'Rufen Sie die Taxizentrale an oder prüfen Sie die Preise im Kalkulator vor Ihrer Fahrt.',
          href: settings.booking_url,
          label: 'Taxi buchen',
        },
      ],
    },
    {
      id: 'services-de',
      locale: 'de',
      slug: 'dienstleistungen',
      eyebrow: 'Dienstleistungen',
      title: 'Fahrzeuge für jede Art von Fahrt.',
      summary: 'Transport für Gruppen, Gepäck, Rollstuhlfahrer, Touristen und Alltagsreisen.',
      blocks: [],
    },
    {
      id: 'fares-de',
      locale: 'de',
      slug: 'fares',
      eyebrow: 'Preise',
      title: 'Klare Preise und schnelle Schätzungen.',
      summary: 'Nutzen Sie den Kalkulator oder rufen Sie die Zentrale für geplante Fahrten an.',
      blocks: [],
    },
    {
      id: 'gallery-de',
      locale: 'de',
      slug: 'galerie',
      eyebrow: 'Galerie',
      title: 'Voss Taxi auf der Straße.',
      summary: 'Eine kleine Auswahl unseres Fuhrparks und des täglichen Taxibetriebs in Voss.',
      blocks: [],
    },
    {
      id: 'contact-de',
      locale: 'de',
      slug: 'kontakt',
      eyebrow: 'Kontakt',
      title: 'Kontaktieren Sie Voss Taxi.',
      summary: 'Rufen Sie die Zentrale an, senden Sie eine E-Mail oder finden Sie uns in der Uttrågata.',
      blocks: [],
    },
  ],
  services: [
    {
      id: 'service-de-1',
      locale: 'de',
      title: 'FLUGHAFEN',
      description: 'Wenn Sie fliegen, fahren wir Sie zum Flughafen Flesland und holen Sie auch dort ab. Rufen Sie an oder senden Sie uns eine E-Mail für weitere Informationen und Festpreise.',
      capacity: '1-16 Passagiere',
      sort: 1,
    },
    {
      id: 'service-de-2',
      locale: 'de',
      title: 'ROLLSTUHL',
      description: 'Voss Taxi verfügt über einen vielfältigen Fuhrpark mit Platz für klappbare Rollstühle. Für elektrische Rollstühle haben wir zwei 16-Sitzer Maxi-Taxis und drei 8-Sitzer Rollstuhlautos mit Rampen.',
      capacity: 'Bis zu 2 Rollstühle',
      sort: 2,
    },
    {
      id: 'service-de-3',
      locale: 'de',
      title: 'FUNDBÜRO',
      description: 'Haben Sie etwas verloren? Kontaktieren Sie uns. Wir bewahren alle in unseren Fahrzeugen gefundenen Gegenstände in unserer Zentrale auf.',
      capacity: '',
      sort: 3,
    },
    {
      id: 'service-de-4',
      locale: 'de',
      title: 'KINDER IM AUTO',
      description: 'Wir haben Kindersitze mit IsoFix für alle Altersgruppen. Zusätzlich haben wir eine große Auswahl an Sitzerhöhungen.',
      capacity: '',
      sort: 4,
    },
    {
      id: 'service-de-5',
      locale: 'de',
      title: 'FAHRRAD?',
      description: 'Wir können auch Fahrräder mitnehmen. Bitte informieren Sie uns im Voraus, damit wir einen Fahrradträger mitbringen können.',
      capacity: '',
      sort: 5,
    },
    {
      id: 'service-de-6',
      locale: 'de',
      title: 'BLINDENHUND',
      description: 'Alle unsere Autos und Fahrer nehmen Hunde mit.',
      capacity: '',
      sort: 6,
    },
  ],
  fares: [
    { id: 'fare-phone-de', locale: 'de', label: 'Zentrale', value: '56 51 13 40', note: 'Anrufen für Buchung und Preise', sort: 1 },
    { id: 'fare-calc-de', locale: 'de', label: 'Kalkulator', value: 'Online', note: 'Geschätzten Preis vor der Fahrt prüfen', sort: 2 },
    { id: 'fare-app-de', locale: 'de', label: 'App', value: 'Snappy Taxi', note: 'Über App aus dem App Store oder Google Play buchen', sort: 3 },
  ],
  gallery: deGallery,
  quickLinks: [
    {
      id: 'link-airport-de',
      locale: 'de',
      title: 'Flughafentransfer',
      description: 'Sichere Fahrt nach Flesland',
      href: '/de/dienstleistungen',
      label: 'Lesen Sie mehr',
      sort: 1,
    },
    {
      id: 'link-wheelchair-de',
      locale: 'de',
      title: 'Rollstuhlgerecht',
      description: 'Speziell ausgestattete Fahrzeuge mit Rampe',
      href: '/de/dienstleistungen',
      label: 'Lesen Sie mehr',
      sort: 2,
    },
  ],
}
