import type { SiteData } from '../types'
import { settings, originalGalleryImages } from './shared'

const frGallery: SiteData['gallery'] = originalGalleryImages.map(([title, alt, image]: string[], index: number) => ({
  id: `gallery-original-fr-${index + 1}`,
  locale: 'fr',
  title,
  alt,
  image,
  sort: index + 1,
}))

export const fallbackFr: SiteData = {
  settings,
  source: 'fallback',
  navigation: [
    { id: 'nav-home-fr', locale: 'fr', label: 'Accueil', href: '/fr', sort: 1 },
    { id: 'nav-om-oss-fr', locale: 'fr', label: 'À propos', href: '/fr/a-propos', sort: 2 },
    { id: 'nav-services-fr', locale: 'fr', label: 'Services', href: '/fr/services', sort: 3 },
    { id: 'nav-pakker-fr', locale: 'fr', label: 'Forfaits', href: '/fr/forfaits', sort: 4 },
    { id: 'nav-maxi-taxi-fr', locale: 'fr', label: 'Maxi Taxi', href: '/fr/maxi-taxi', sort: 6 },
    { id: 'nav-bli-sjafor-fr', locale: 'fr', label: 'Devenir chauffeur', href: '/fr/devenir-chauffeur', sort: 7 },
    { id: 'nav-gallery-fr', locale: 'fr', label: 'Galerie', href: '/fr/galerie', sort: 8 },
    { id: 'nav-ris-ros-fr', locale: 'fr', label: 'Avis', href: '/fr/avis', sort: 9 },
    { id: 'nav-contact-fr', locale: 'fr', label: 'Contact', href: '/fr/contact', sort: 10 },
  ],
  pages: [
    {
      id: 'home-fr',
      locale: 'fr',
      slug: 'home',
      eyebrow: 'Compagnie de taxi locale à Voss',
      title: 'Conduisez en toute sécurité avec nous, depuis Voss.',
      summary:
        'Voss Taxi propose des berlines, des mini-fourgonnettes, des maxi-taxis, des minibus et des transports en fauteuil roulant pour les locaux et les visiteurs.',
      hero_image: settings.hero_media,
      blocks: [
        {
          type: 'rich_text',
          title: 'Réservez en toute confiance',
          body: 'Nous avons des véhicules pour tous les types de missions et vous accompagnerons en toute sécurité vers et depuis les trains, les hôtels, les chalets, les montagnes et les événements.',
        },
        {
          type: 'rich_text',
          title: 'Réserver via l\'application',
          body: '### Snappy Taxi\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/snappy-taxi/id6479620974) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=no.snappy.snappy.taxi&hl=no)\n\n### Réserver un taxi dans l\'application VY\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/vy-nsb/id439655098) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=com.intele.nsbmob.app)'
        },
        {
          type: 'cta',
          title: 'Réserver par téléphone ou calculateur',
          body: 'Appelez la centrale de taxi ou vérifiez les prix dans le calculateur avant votre voyage.',
          href: settings.booking_url,
          label: 'Réserver un taxi',
        },
      ],
    },
    {
      id: 'services-fr',
      locale: 'fr',
      slug: 'tenester',
      eyebrow: 'Services',
      title: 'Des véhicules pour chaque type de trajet.',
      summary: 'Transport pour les groupes, les bagages, les utilisateurs de fauteuils roulants, les touristes et les trajets quotidiens.',
      blocks: [],
    },
    {
      id: 'fares-fr',
      locale: 'fr',
      slug: 'tarifs',
      eyebrow: 'Tarifs',
      title: 'Des tarifs clairs et des estimations rapides.',
      summary: 'Utilisez le calculateur ou appelez la centrale pour les trajets planifiés.',
      blocks: [],
    },
    {
      id: 'gallery-fr',
      locale: 'fr',
      slug: 'galleri',
      eyebrow: 'Galerie',
      title: 'Voss Taxi sur la route.',
      summary: 'Une petite sélection de notre flotte et du service de taxi quotidien à Voss.',
      blocks: [],
    },
    {
      id: 'contact-fr',
      locale: 'fr',
      slug: 'kontakt',
      eyebrow: 'Contact',
      title: 'Contactez Voss Taxi.',
      summary: 'Appelez la centrale, envoyez un e-mail ou trouvez-nous à Uttrågata.',
      blocks: [],
    },
  ],
  services: [
    {
      id: 'service-fr-1',
      locale: 'fr',
      title: 'AÉROPORT',
      description: 'Si vous prenez l\'avion, nous vous conduirons à l\'aéroport de Flesland. Appelez-nous ou envoyez un e-mail pour plus d\'informations et des prix fixes.',
      capacity: '1-16 passagers',
      sort: 1,
    },
    {
      id: 'service-fr-2',
      locale: 'fr',
      title: 'FAUTEUIL ROULANT',
      description: 'Voss Taxi dispose d\'une flotte variée avec de l\'espace pour les fauteuils roulants pliables. Pour les fauteuils électriques, nous avons deux Maxi-Taxis de 16 places et trois voitures pour fauteuils roulants de 8 places avec rampes.',
      capacity: 'Jusqu\'à 2 fauteuils roulants',
      sort: 2,
    },
    {
      id: 'service-fr-3',
      locale: 'fr',
      title: 'OBJETS TROUVÉS',
      description: 'Avez-vous perdu quelque chose? Contactez-nous. Tous les objets trouvés dans nos voitures sont conservés à notre centrale.',
      capacity: '',
      sort: 3,
    },
    {
      id: 'service-fr-4',
      locale: 'fr',
      title: 'ENFANTS EN VOITURE',
      description: 'Nous avons des sièges enfants avec IsoFix pour tous les âges. De plus, nous avons un large choix de rehausseurs.',
      capacity: '',
      sort: 4,
    },
    {
      id: 'service-fr-5',
      locale: 'fr',
      title: 'VÉLO ?',
      description: 'Nous pouvons également transporter des vélos. Veuillez nous en informer à l\'avance afin que nous puissions apporter un porte-vélo.',
      capacity: '',
      sort: 5,
    },
    {
      id: 'service-fr-6',
      locale: 'fr',
      title: 'CHIEN D\'AVEUGLE',
      description: 'Toutes nos voitures et nos chauffeurs acceptent les chiens.',
      capacity: '',
      sort: 6,
    },
  ],
  fares: [
    { id: 'fare-phone-fr', locale: 'fr', label: 'Centrale', value: '56 51 13 40', note: 'Appelez pour réservation et prix', sort: 1 },
    { id: 'fare-calc-fr', locale: 'fr', label: 'Calculateur', value: 'En ligne', note: 'Vérifiez le prix estimé avant le trajet', sort: 2 },
    { id: 'fare-app-fr', locale: 'fr', label: 'Appli', value: 'Snappy Taxi', note: 'Réservez via l\'application sur App Store ou Google Play', sort: 3 },
  ],
  gallery: frGallery,
  quickLinks: [
    {
      id: 'link-airport-fr',
      locale: 'fr',
      title: 'Transfert Aéroport',
      description: 'Trajet en toute sécurité vers Flesland',
      href: '/fr/services',
      label: 'En savoir plus',
      sort: 1,
    },
    {
      id: 'link-wheelchair-fr',
      locale: 'fr',
      title: 'Accessible en fauteuil roulant',
      description: 'Véhicules spécialement équipés avec rampe',
      href: '/fr/services',
      label: 'En savoir plus',
      sort: 2,
    },
  ],
}
