import type { SiteData } from '../types'
import { settings, originalGalleryImages } from './fallback'

const esGallery: SiteData['gallery'] = originalGalleryImages.map(([title, alt, image]: string[], index: number) => ({
  id: `gallery-original-es-${index + 1}`,
  locale: 'es',
  title,
  alt,
  image,
  sort: index + 1,
}))

export const fallbackEs: SiteData = {
  settings,
  source: 'fallback',
  navigation: [
    { id: 'nav-home-es', locale: 'es', label: 'Inicio', href: '/es', sort: 1 },
    { id: 'nav-om-oss-es', locale: 'es', label: 'Sobre nosotros', href: '/es/sobre-nosotros', sort: 2 },
    { id: 'nav-services-es', locale: 'es', label: 'Servicios', href: '/es/servicios', sort: 3 },
    { id: 'nav-pakker-es', locale: 'es', label: 'Paquetes', href: '/es/paquetes', sort: 4 },
    { id: 'nav-maxi-taxi-es', locale: 'es', label: 'Maxi Taxi', href: '/es/maxi-taxi', sort: 6 },
    { id: 'nav-bli-sjafor-es', locale: 'es', label: 'Hazte conductor', href: '/es/hazte-conductor', sort: 7 },
    { id: 'nav-gallery-es', locale: 'es', label: 'Galería', href: '/es/galeria', sort: 8 },
    { id: 'nav-ris-ros-es', locale: 'es', label: 'Opiniones', href: '/es/opiniones', sort: 9 },
    { id: 'nav-contact-es', locale: 'es', label: 'Contacto', href: '/es/contacto', sort: 10 },
  ],
  pages: [
    {
      id: 'home-es',
      locale: 'es',
      slug: 'home',
      eyebrow: 'Compañía de taxis local en Voss',
      title: 'Conduce seguro con nosotros, desde Voss.',
      summary:
        'Voss Taxi ofrece berlinas, monovolúmenes, maxi-taxis, minibuses y transporte en silla de ruedas para lugareños y visitantes.',
      hero_image: settings.hero_media,
      blocks: [
        {
          type: 'rich_text',
          title: 'Reserva con confianza',
          body: 'Tenemos vehículos para todo tipo de encargos y le llevaremos con seguridad desde y hacia trenes, hoteles, cabañas, montañas y eventos.',
        },
        {
          type: 'rich_text',
          title: 'Reservar a través de la aplicación',
          body: '### Snappy Taxi\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/snappy-taxi/id6479620974) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=no.snappy.snappy.taxi&hl=no)\n\n### Reservar un taxi en la aplicación VY\n\n[![](/images/app-store.png)](https://apps.apple.com/no/app/vy-nsb/id439655098) [![](/images/google-play.png)](https://play.google.com/store/apps/details?id=com.intele.nsbmob.app)'
        },
        {
          type: 'cta',
          title: 'Reservar por teléfono o calculadora',
          body: 'Llame a la central de taxis o compruebe los precios en la calculadora antes de su viaje.',
          href: settings.booking_url,
          label: 'Reservar un taxi',
        },
      ],
    },
    {
      id: 'services-es',
      locale: 'es',
      slug: 'servicios',
      eyebrow: 'Servicios',
      title: 'Vehículos para cada tipo de viaje.',
      summary: 'Transporte para grupos, equipaje, usuarios de sillas de ruedas, turistas y viajes diarios.',
      blocks: [],
    },
    {
      id: 'fares-es',
      locale: 'es',
      slug: 'tarifas',
      eyebrow: 'Tarifas',
      title: 'Tarifas claras y estimaciones rápidas.',
      summary: 'Utilice la calculadora o llame a la central para viajes planificados.',
      blocks: [],
    },
    {
      id: 'gallery-es',
      locale: 'es',
      slug: 'galeria',
      eyebrow: 'Galería',
      title: 'Voss Taxi en la carretera.',
      summary: 'Una pequeña selección de nuestra flota y del servicio de taxi diario en Voss.',
      blocks: [],
    },
    {
      id: 'contact-es',
      locale: 'es',
      slug: 'contacto',
      eyebrow: 'Contacto',
      title: 'Contacte con Voss Taxi.',
      summary: 'Llame a la central, envíe un correo electrónico o encuéntrenos en Uttrågata.',
      blocks: [],
    },
  ],
  services: [
    {
      id: 'service-es-1',
      locale: 'es',
      title: 'AEROPUERTO',
      description: 'Si va a volar, le llevaremos al aeropuerto de Flesland. Llámenos o envíenos un correo electrónico para obtener más información y precios fijos.',
      capacity: '1-16 pasajeros',
      sort: 1,
    },
    {
      id: 'service-es-2',
      locale: 'es',
      title: 'SILLA DE RUEDAS',
      description: 'Voss Taxi cuenta con una flota variada con espacio para sillas de ruedas plegables. Para sillas de ruedas eléctricas, tenemos dos Maxi-Taxis de 16 plazas y tres coches para sillas de ruedas de 8 plazas con rampas.',
      capacity: 'Hasta 2 sillas de ruedas',
      sort: 2,
    },
    {
      id: 'service-es-3',
      locale: 'es',
      title: 'OBJETOS PERDIDOS',
      description: '¿Ha perdido algo? Contáctenos. Todos los objetos encontrados en nuestros coches se guardan en nuestra central.',
      capacity: '',
      sort: 3,
    },
    {
      id: 'service-es-4',
      locale: 'es',
      title: 'NIÑOS EN EL COCHE',
      description: 'Tenemos sillas para niños con IsoFix para todas las edades. Además, disponemos de una amplia selección de alzadores.',
      capacity: '',
      sort: 4,
    },
    {
      id: 'service-es-5',
      locale: 'es',
      title: '¿BICICLETA?',
      description: 'También podemos llevar bicicletas. Por favor, infórmenos con antelación para que podamos llevar un portabicicletas.',
      capacity: '',
      sort: 5,
    },
    {
      id: 'service-es-6',
      locale: 'es',
      title: 'PERRO GUÍA',
      description: 'Todos nuestros coches y conductores aceptan perros.',
      capacity: '',
      sort: 6,
    },
  ],
  fares: [
    { id: 'fare-phone-es', locale: 'es', label: 'Central', value: '56 51 13 40', note: 'Llamar para reservar y precios', sort: 1 },
    { id: 'fare-calc-es', locale: 'es', label: 'Calculadora', value: 'En línea', note: 'Comprobar el precio estimado antes del viaje', sort: 2 },
    { id: 'fare-app-es', locale: 'es', label: 'App', value: 'Snappy Taxi', note: 'Reserva a través de la aplicación en la App Store o Google Play', sort: 3 },
  ],
  gallery: esGallery,
  quickLinks: [
    {
      id: 'link-airport-es',
      locale: 'es',
      title: 'Traslado al aeropuerto',
      description: 'Viaje seguro a Flesland',
      href: '/es/servicios',
      label: 'Leer más',
      sort: 1,
    },
    {
      id: 'link-wheelchair-es',
      locale: 'es',
      title: 'Accesible para sillas de ruedas',
      description: 'Vehículos especialmente equipados con rampa',
      href: '/es/servicios',
      label: 'Leer más',
      sort: 2,
    },
  ],
}
