import type { Locale } from '../types'

export const uiStrings = {
  no: {
    callNow: 'Ring no',
    bookOnline: 'Ting på nett',
    liveDispatch: 'Live sentral',
    ready: 'Klar',
    bookYourTrip: 'Ting tur',
    taxiOnVoss: 'Taxi på Voss, utan ventetid.',
    callDispatch: 'Ring sentralen',
    onlineBooking: 'Tinging på nett',
    startBooking: 'Start tinging',
    fareEstimate: 'Priskalkulator',
    checkPrice: 'Sjekk pris',
    localDrivers: 'Lokale sjåførar, kjende vegar og førehandstinging.',
    services: 'Tenester',
    fleetOverview: 'Eit ryddigare overblikk over bilparken.',
    fares: 'Takstar',
    fastChoices: 'Raske val før turen.',
    dispatch: 'Sentral',
    wheelchairs: 'Rullestolbilar',
    electricManual: 'Elektrisk og manuell',
    groups: 'Grupper',
  },
  en: {
    callNow: 'Call now',
    bookOnline: 'Book online',
    liveDispatch: 'Live dispatch',
    ready: 'Ready',
    bookYourTrip: 'Book your trip',
    taxiOnVoss: 'Taxi on Voss, without waiting.',
    callDispatch: 'Call dispatch',
    onlineBooking: 'Online booking',
    startBooking: 'Start booking',
    fareEstimate: 'Fare estimate',
    checkPrice: 'Check price',
    localDrivers: 'Local drivers, known roads and pre-booked trips.',
    services: 'Services',
    fleetOverview: 'A cleaner overview of the fleet.',
    fares: 'Fares',
    fastChoices: 'Fast choices before the trip.',
    dispatch: 'Dispatch',
    wheelchairs: 'Wheelchairs',
    electricManual: 'Electric & manual',
    groups: 'Groups',
  },
  de: {
    callNow: 'Jetzt anrufen',
    bookOnline: 'Online buchen',
    liveDispatch: 'Live-Zentrale',
    ready: 'Bereit',
    bookYourTrip: 'Fahrt buchen',
    taxiOnVoss: 'Taxi in Voss, ohne Wartezeiten.',
    callDispatch: 'Zentrale anrufen',
    onlineBooking: 'Online-Buchung',
    startBooking: 'Buchung starten',
    fareEstimate: 'Preisrechner',
    checkPrice: 'Preis prüfen',
    localDrivers: 'Lokale Fahrer, bekannte Straßen und vorgebuchte Fahrten.',
    services: 'Dienstleistungen',
    fleetOverview: 'Ein sauberer Überblick über den Fuhrpark.',
    fares: 'Preise',
    fastChoices: 'Schnelle Auswahl vor der Fahrt.',
    dispatch: 'Zentrale',
    wheelchairs: 'Rollstuhltaxis',
    electricManual: 'Elektrisch & manuell',
    groups: 'Gruppen',
  },
  fr: {
    callNow: 'Appeler maintenant',
    bookOnline: 'Réserver en ligne',
    liveDispatch: 'Centrale en direct',
    ready: 'Prêt',
    bookYourTrip: 'Réservez votre trajet',
    taxiOnVoss: 'Taxi à Voss, sans attendre.',
    callDispatch: 'Appeler la centrale',
    onlineBooking: 'Réservation en ligne',
    startBooking: 'Démarrer la réservation',
    fareEstimate: 'Estimation du prix',
    checkPrice: 'Vérifier le prix',
    localDrivers: 'Chauffeurs locaux, routes connues et trajets pré-réservés.',
    services: 'Services',
    fleetOverview: 'Un aperçu plus clair de la flotte.',
    fares: 'Tarifs',
    fastChoices: 'Choix rapides avant le voyage.',
    dispatch: 'Centrale',
    wheelchairs: 'Fauteuils roulants',
    electricManual: 'Électrique et manuel',
    groups: 'Groupes',
  },
  es: {
    callNow: 'Llamar ahora',
    bookOnline: 'Reservar en línea',
    liveDispatch: 'Central en vivo',
    ready: 'Listo',
    bookYourTrip: 'Reserva tu viaje',
    taxiOnVoss: 'Taxi en Voss, sin esperas.',
    callDispatch: 'Llamar a la central',
    onlineBooking: 'Reserva en línea',
    startBooking: 'Iniciar reserva',
    fareEstimate: 'Calculadora de precios',
    checkPrice: 'Comprobar precio',
    localDrivers: 'Conductores locales, rutas conocidas y viajes reservados.',
    services: 'Servicios',
    fleetOverview: 'Una visión clara de nuestra flota.',
    fares: 'Tarifas',
    fastChoices: 'Opciones rápidas antes del viaje.',
    dispatch: 'Central',
    wheelchairs: 'Sillas de ruedas',
    electricManual: 'Eléctricas y manuales',
    groups: 'Grupos',
  }
}

export function useUI(locale: Locale) {
  return uiStrings[locale] || uiStrings.no
}
